// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtOZ-hQbNMHbJv1C3MhdWgWcogl2dx93Q',
    appId: '1:1098338880355:web:8485689f9ac2daa70fe156',
    messagingSenderId: '1098338880355',
    projectId: 'malai-sodhnus-ask-anything',
    authDomain: 'malai-sodhnus-ask-anything.firebaseapp.com',
    storageBucket: 'malai-sodhnus-ask-anything.appspot.com',
    measurementId: 'G-RP2CYXKLDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUY7bAPeAvro_UleZ2JO8UIZDpay2kf0Y',
    appId: '1:1098338880355:android:0104ce708066a4400fe156',
    messagingSenderId: '1098338880355',
    projectId: 'malai-sodhnus-ask-anything',
    storageBucket: 'malai-sodhnus-ask-anything.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1dY98hZi5t391C4K4LICl2mermmLG-8I',
    appId: '1:1098338880355:ios:ea63677831ec20a80fe156',
    messagingSenderId: '1098338880355',
    projectId: 'malai-sodhnus-ask-anything',
    storageBucket: 'malai-sodhnus-ask-anything.appspot.com',
    iosClientId: '1098338880355-jl4k1ucpa12frvm1k72ev6m2i7rk6km7.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1dY98hZi5t391C4K4LICl2mermmLG-8I',
    appId: '1:1098338880355:ios:ea63677831ec20a80fe156',
    messagingSenderId: '1098338880355',
    projectId: 'malai-sodhnus-ask-anything',
    storageBucket: 'malai-sodhnus-ask-anything.appspot.com',
    iosClientId: '1098338880355-jl4k1ucpa12frvm1k72ev6m2i7rk6km7.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstProject',
  );
}
